### ISSUE TITLE
ByteArray.write64_be is faulty in WriteBits.kt

### ISSUE THREAD

**Issue by Moonlight-Angel** [korlibs/kmem#1]
Hi,

Just a quick issue to report that there's a problem in `ByteArray.write64_be` (affecting both `AsyncStream` and `SyncStream` in korio – from what I saw).
It's writing two integers in **little endian** instead of writing them in **big endian**.
Right here, at this line : https://github.com/korlibs/kmem/blob/master/kmem/common/src/main/kotlin/com/soywiz/kmem/WriteBits.kt#L26

Sorry for not making a PR for such a tiny change.
Regards.

**Comment by soywiz** [comment]
Yeah. It took me a full year :) Sorry I was not watching the repo (I had disabled automatic watching for new repos). I have just noticed and now I am watching all my repos.

Thanks for the report! It went totally unnoticed for such a long time.
